// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class convocationreq_db_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(convocationreq_db_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202404271210583_convocationreq_db_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
