// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Certification_db_seeding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Certification_db_seeding));
        
        string IMigrationMetadata.Id
        {
            get { return "202404271231541_Certification_db_seeding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
